### ISSUE TITLE
Update inventory data in StEWI through 2023

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#275]

**Comment by bl-young** [comment]
In v1.2 of StEWI, data are available through 2023, except for NEI, therefore the inventories of interest might look like:
```
inventories_of_interest:
  eGRID: 2023
  TRI: 2023
  NEI: 2022
  RCRAInfo: 2023
```
